anki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from cards import views
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('cards/', include('cards.urls')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

cards/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('catalog/', cache_page(60*15)(views.CatalogView.as_view()), name='catalog'),
    path('categories/', views.get_categories, name='categories'),
    path('categories/<slug:slug>/', views.get_cards_by_category, name='category'),
    path('tags/<int:tag_id>/', views.get_cards_by_tag, name='get_cards_by_tag'),
    path('<int:pk>/detail/', views.CardDetailView.as_view(), name='detail_card_by_id'),
    path('add/', views.AddCardCreateView.as_view(), name='add_card'),
    path('<int:pk>/edit/', views.CardUpdateView.as_view(), name='edit_card'),
    path('preview_card_ajax/', views.preview_card_ajax, name='preview_card_ajax'),
]

cards/models.py
from django.db import models
from django.urls import reverse
import logging
from django.contrib.auth import get_user_model

# Создаем или получаем экземпляр логгера
logger = logging.getLogger(__name__)

# Устанавливаем базовый уровень логирования
logging.basicConfig(level=logging.DEBUG)

# Create your models here.
class Card(models.Model):
     class Status(models.IntegerChoices):
         UNCHECKED = 0, 'Не проверено'
         CHECKED = 1, 'Проверено'

     card_id = models.AutoField(primary_key=True, db_column="CardID")
     question = models.TextField(db_column="Question")
     answer = models.TextField(db_column="Answer")
     category_id = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, db_column="CategoryID", verbose_name="Категория")
     upload_date = models.DateTimeField(auto_now_add=True, db_column="UploadDate", verbose_name="Дата загрузки")
     views = models.IntegerField(default=0, db_column="Views")
     favorites = models.IntegerField(default=0, db_column="Favorites")
     check_status = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),default=Status.UNCHECKED, db_column='CheckStatus')
     tags = models.ManyToManyField('Tag', related_name='cards', through="CardTags")
     author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, db_column='AuthorID', related_name='cards', null=True, default=None, verbose_name='Автор')


     # Расширение нашего класса
     class Meta:
         db_table = 'Cards'
         verbose_name = 'Карточка'
         verbose_name_plural = 'Карточки'

     def __str__(self):
         return self.question

     def get_absolute_url(self):
         return reverse('detail_card_by_id', kwargs={'pk': self.card_id})

     def save(self, *args, **kwargs):
         logger.debug(f'Сохранение карточки {self.card_id} значение {self.__dict__}')

         super().save(*args, **kwargs)


class Category(models.Model):
    category_id = models.AutoField(primary_key=True, db_column="CategoryID")
    name = models.CharField(max_length=100, unique=True, db_column="Name")

    class Meta:
        db_table = "Categories"
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

class User(models.Model):
    user_id = models.AutoField(primary_key=True, db_column="UserID")
    user_name = models.TextField(max_length=100, db_column="UserName")

    class Meta:
        db_table = "Users"
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.user_name

class Tag(models.Model):
    tag_id = models.AutoField(primary_key=True, db_column="TagID")
    name = models.CharField(max_length=50, unique=True, db_column="Name")

    class Meta:
        db_table = "Tags"
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name


class CardTags(models.Model):
    id = models.AutoField(primary_key=True, db_column='id')
    card = models.ForeignKey('Card', on_delete=models.CASCADE, db_column='CardID')
    tag = models.ForeignKey('Tag', on_delete=models.CASCADE, db_column='TagID')

    class Meta:
        db_table = 'CardTags'
        verbose_name = 'Связь карточка-тег'
        verbose_name_plural = 'Связи карточка-тег'

    def __str__(self):
        return f'{self.card} - {self.tag}'

cards/forms.py
from django import forms
from cards.models import Category, Card, Tag


class CardModelForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Категория не выбрана", label="Категории")
    tags = forms.CharField(label="Теги", required=False, help_text="Перечислите теги чере запятую")


    class Meta:
        model = Card
        fields = ['question', 'answer', 'category', 'tags']
        widgets = {
            'question': forms.TextInput(attrs={'class': 'form-control'}),
            'answer': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'cols': 40}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'tags': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'question': 'Вопрос',
            'answer': 'Ответ'
        }



    def save(self, *args, **kwargs):
        instance = super().save(commit=False)
        instance.save()

        self.instance.tags.clear()

        tag_names = self.cleaned_data['tags'].split(',')
        for tag_name in tag_names:
            tag_name = tag_name.strip()
            if tag_name:
                tag, created = Tag.objects.get_or_create(name=tag_name)
                self.instance.tags.add(tag)

        return instance

cards/views.py
"""
get_all_cards - возвращает все карточки для представления в каталоге
get_categories - возвращает все категории для представления в каталоге
get_cards_by_category - возвращает карточки по категории для представления в каталоге
get_cards_by_tag - возвращает карточки по тегу для представления в каталоге
get_detail_card_by_id - возвращает детальную информацию по карточке для представления
"""
from linecache import cache
from django.db.models import F, Q, Prefetch
from django.http import HttpResponse, JsonResponse
from .models import Card
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.cache import cache_page
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import CardModelForm
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.views import View
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

info = {
    'users_info': 100500,
    'cards_count': 200600,
    'menu': [
        {'title': 'Главная',
         'url_name': 'index'},
        {'title': 'О проекте',
         'url_name': 'about'},
        {'title': 'Каталог',
         'url_name': 'catalog'}
    ],
}

class MenuMixin:
    def get_context_data(self, **kwargs):
        # Вызываем родительский метод, чтобы получить контекст представления
        context = super().get_context_data(**kwargs)
        # Добавляем информацию о меню в контекст
        context['menu'] = info['menu']
        return context

class IndexView(TemplateView):
    template_name = 'main.html'  # Указываем имя шаблона для отображения
    # Предполагаем, что info - это словарь с данными, который мы хотим передать в шаблон
    extra_context = info


class AboutView(TemplateView):
    template_name = 'about.html'  # Аналогично указываем имя шаблона
    extra_context = info

class CatalogView(ListView):
    model = Card  # Указываем модель, данные которой мы хотим отобразить
    template_name = 'cards/catalog.html'  # Путь к шаблону, который будет использоваться для отображения страницы
    context_object_name = 'cards'  # Имя переменной контекста, которую будем использовать в шаблоне
    paginate_by = 30  # Количество объектов на странице

    def get_queryset(self):
        # Получение параметров сортировки из GET-запроса
        sort = self.request.GET.get('sort', 'upload_date')
        order = self.request.GET.get('order', 'desc')
        search_query = self.request.GET.get('search_query', '')

        # Определение направления сортировки
        if order == 'asc':
            order_by = sort
        else:
            order_by = f'-{sort}'

        queryset = Card.objects.prefetch_related('tags').all()

        # Фильтрация карточек по поисковому запросу и сортировка
        # select_related - для оптимизации запроса, чтобы избежать дополнительных запросов к БД
        if search_query:
            queryset = queryset.filter(
                Q(question__icontains=search_query) |
                Q(answer__icontains=search_query) |
                Q(tags__name__icontains=search_query)
            ).distinct().order_by(order_by)
        else:
            queryset = queryset.order_by(order_by)

        return queryset

    def get_context_data(self, **kwargs):
        # Получение существующего контекста из базового класса
        context = super().get_context_data(**kwargs)
        # Добавление дополнительных данных в контекст
        context['sort'] = self.request.GET.get('sort', 'upload_date')
        context['order'] = self.request.GET.get('order', 'desc')
        context['search_query'] = self.request.GET.get('search_query', '')

        return context


def get_categories(request):
    return render(request, 'base.html', context=info)

def get_cards_by_category(request, slug):
    return HttpResponse(f'Cards by category {slug}')

@cache_page(60 * 15)
def get_cards_by_tag(request, tag_id):
    """
    Возвращает карточки по тегу для представления в каталоге
    Мы используем многие-ко-многим, получая все карточки, которые связаны с тегом
    Временно, мы будем использовать шаблон каталога
    """
    # cards = Card.objects.filter(tags=tag_id)

    # Жадная загрузка
    cards = Card.objects.filter(tags=tag_id).prefetch_related('tags')
    context = {
        'cards': cards,
        'cards_count': cards.count(),
        'menu': info['menu'],
    }
    return render(request, 'cards/catalog.html', context)


def get_detail_card_by_id(request, card_id):
    card_obj = get_object_or_404(Card.objects.prefetch_related('tags'), pk=card_id)

    # Обновление счетчика просмотров
    Card.objects.filter(pk=card_id).update(views=F('views') + 1)

    card = {
        "card": card_obj,
        "menu": info["menu"],
    }

    return render(request, 'cards/card_detail.html', card, status=200)

class CardDetailView(DetailView):
    model = Card
    template_name = 'cards/card_detail.html'
    context_object_name = 'card'

    # Метод для обновления счетчика просмотров при каждом отображении детальной страницы карточки
    def get_object(self, queryset=None):
        # Получаем объект с учетом переданных в URL параметров (в данном случае, pk или id карточки)
        obj = super().get_object(queryset=queryset)
        # Увеличиваем счетчик просмотров на 1 с помощью F-выражения для избежания гонки условий
        Card.objects.filter(pk=obj.pk).update(views=F('views') + 1)

        # Получаем обновленный объект из БД (+1 запрос в БД)
        obj.refresh_from_db()
        return obj


class CardUpdateView(LoginRequiredMixin, UpdateView):
    model = Card  # Указываем модель, с которой работает представление
    form_class = CardModelForm  # Указываем класс формы для создания карточки
    template_name = 'cards/add_card.html'  # Указываем шаблон, который будет использоваться для отображения формы
    login_url = reverse_lazy('users:login')  # Для перенаправления на главную страницу
    redirect_field_name = 'next'

    # После успешного обновления карточки, пользователь будет перенаправлен на страницу этой карточки
    def get_success_url(self):
        return reverse_lazy('catalog', kwargs={'pk': self.object.pk})


class AddCardCreateView(LoginRequiredMixin, CreateView):
    model = Card  # Указываем модель, с которой работает представление
    form_class = CardModelForm  # Указываем класс формы для создания карточки
    template_name = 'cards/add_card.html'  # Указываем шаблон, который будет использоваться для отображения формы
    success_url = reverse_lazy('catalog')
    login_url = reverse_lazy('users:login') # Для перенаправления на главную страницу
    redirect_field_name = 'next'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



def preview_card_ajax(request):
    if request.method == "POST":
        question = request.POST.get('question', '')
        answer = request.POST.get('answer', '')
        category = request.POST.get('category', '')

        # Генерация HTML для предварительного просмотра
        html_content = render_to_string('cards/card_detail.html', {
            'card': {
                'question': question,
                'answer': answer,
                'category': 'Тестовая категория',
                'tags': ['тест', 'тег'],

            }
        })
        return JsonResponse({'html': html_content})
    return HttpResponseRedirect('cards/add/')

cards/templates/cards/add_card.html
{% extends 'base.html' %}
{% block content %}
    <h1>Добавить карточку</h1>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-lg-6">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                            {% if field.errors %}
                                <div class="alert alert-danger mt-1">{{ field.errors.as_text }}</div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="mb-3">
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger">{{ form.non_field_errors }}</div>
                        {% endif %}
                    </div>
                    <button type="submit" class="btn btn-dark">Отправить</button>
                </form>
            </div>
            <div class="col-12 col-lg-6">
                <div id="preview-container" class="shadow-lg p-3 mb-5 bg-white rounded">
                    <!-- Сюда будет вставлен предварительный просмотр -->
                    ЭТО КОНТЕНТ ПРЕДВАРИТЕЛЬНОГО ПРОСМОТРА
                </div>
            </div>
        </div>
    </div>

    <script>
        console.log('preview_card_ajax.js');
        // Получение токена CSRF
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

            document.addEventListener('DOMContentLoaded', () => {

            const questionInput = document.querySelector('#id_question'); // ID поля вопроса в вашей форме
            const answerInput = document.querySelector('#id_answer'); // ID поля ответа
            const previewContainer = document.querySelector('#preview-container'); // Контейнер для вставки предварительного просмотра
            const csrftoken = getCookie('csrftoken'); // Получение токена CSRF
            let timeout = null;

            console.log(`csrftoken: ${csrftoken}`)

            const fetchPreview = async () => {
                const formData = new FormData();
                formData.append('question', questionInput.value);
                formData.append('answer', answerInput.value);

                try {
                    console.log('fetching preview...');
                    const response = await fetch('/cards/preview_card_ajax/', { // Укажите правильный URL
                        method: 'POST',
                        body: formData,
                        headers: {
                            'X-CSRFToken': csrftoken, // csrftoken необходимо определить
                        },
                    });
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }

                    const data = await response.json();
                    previewContainer.innerHTML = data.html;

                    setTimeout(() => hljs.highlightAll(), 100); // небольшая задержка может помочь

                } catch (error) {
                    console.error('Failed to fetch preview:', error);
                }
            };

            const debounceFetchPreview = () => {
                clearTimeout(timeout);
                console.log('debouncing...');
                timeout = setTimeout(fetchPreview, 2000);
            };

            questionInput.addEventListener('input', debounceFetchPreview);
            answerInput.addEventListener('input', debounceFetchPreview);
            });
    </script>
{% endblock %}

cards/templates/cards/card_detail.html
{% extends 'base.html' %}
{% load markdown_to_html %}
{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            Детальное представление карточки
        </div>
        <div class="card-body">
            <h5 class="card-title">{% markdown_to_html card.question %}</h5>
            <p class="card-text">{% markdown_to_html card.answer %}</p>
<!--            <p class="card-text"><small class="text-muted">Категория: {{ card.category }}</small></p>-->
<!--            <p class="card-text"> {% markdown_to_html card.answer %} </p>-->
            <p class="card-text">
                Теги:
                {% for tag in card.tags.all %}
                <span class="badge bg-secondary"><a href="{% url 'get_cards_by_tag' tag_id=tag.pk %}" class="text-white">{{ tag.name }}</a></span>
                {% endfor %}
            </p>
            <p class="card-text"><small class="text-muted">Автор:{{ card.author.username|default:"Неизвестен" }} </small></p>
            <div class="d-flex justify-content-between align-items-center mt-3">
                <a href="{% url 'catalog' %}" class="btn btn-dark">Вернуться к каталогу</a>
                <div>
                    <i class="bi bi-eye"></i> {{ card.views }}
                    <i class="bi bi-star-fill"></i> {{ card.favorites }}
                    <small class="text-muted">Дата загрузки: {{ card.upload_date }}</small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

cards/templates/cards/catalog.html
{% extends "base.html" %}
{% load cache %}
{% block head %}
<style>
/* Стили для темной темы пагинации */
.pagination-dark .page-link {
  background-color: #343a40; /* Темный фон для ссылок */
  color: #ffffff; /* Белый текст */
}
.pagination-dark .page-link:hover {
  background-color: #495057; /* Светлее при наведении */
}
.pagination-dark .page-item.active .page-link {
  background-color: #212529 !important; /* Очень темный фон для активной ссылки */
  border-color: #212529 !important; /* Очень темный бордюр для активной ссылки */
}
.pagination-dark .page-item.active .page-link:hover {
  background-color: #32383e !important; /* Немного светлее цвет фона при наведении */
  border-color: #32383e !important; /* Цвет границы при наведении */
}
/* Стили для радиокнопок */
.form-check-input:checked {
  background-color: #212529 !important; /* Очень темный фон для активной радиокнопки */
  border-color: #212529 !important; /* Очень темный бордюр для активной радиокнопки */
}
</style>
{% endblock %}
{% block content %}
<div class="text-dark bg-light">
    <h1>Каталог карточек Anki для интервального повторения</h1>
    <nav aria-label="Page navigation" class="text-dark">
       <ul class="pagination pagination-dark">
           {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link text-white bg-secondary" href="?page={{ page_obj.previous_page_number }}&sort={{ sort }}&order={{ order }}">Предыдущая</a></li>
           {% endif %}
           {% for num in page_obj.paginator.page_range %}
                <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                    <a class="page-link text-white bg-secondary" href="?page={{ num }}&sort={{ sort }}&order={{ order }}">{{ num }}</a>
                </li>
           {% endfor %}
           {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link text-white bg-secondary" href="?page={{ page_obj.next_page_number }}&sort={{ sort }}&order={{ order }}">Следующая</a></li>
           {% endif %}
       </ul>
    </nav>
    <form action="{% url 'catalog' %}" method="get" class="mb-5 mt-3">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Поиск по карточкам" name="search_query" aria-label="Поиск по карточкам">
            <button class="btn btn-outline-secondary" type="submit">Поиск</button>
        </div>

        <div class="mb-1 d-flex justify-content-start">
            <div><strong>Сортировать по:</strong></div>
            <div class="form-check ms-2">
                <input class="form-check-input" type="radio" name="sort" id="sortUploadDate" value="upload_date" checked>
                <label class="form-check-label" for="sortUploadDate">
                   Дате загрузки
                </label>
            </div>
            <div class="form-check ms-2">
                <input class="form-check-input" type="radio" name="sort" id="sortViews" value="views">
                <label class="form-check-label" for="sortViews">
                   Просмотрам
                </label>
            </div>
            <div class="form-check ms-2">
                <input class="form-check-input" type="radio" name="sort" id="sortFavorites" value="favorites">
                <label class="form-check-label" for="sortFavorites">
                   Избранному
                </label>
            </div>
        </div>

        <div class="mb-1 d-flex justify-content-start">
            <div><strong>Порядок сортировки:</strong></div>
            <div class="form-check ms-2">
                <input class="form-check-input" type="radio" name="order" id="sortOrderDesc" value="desc" checked>
                <label class="form-check-label" for="sortUploadDate">
                    Убыванию
                </label>
            </div>
            <div class="form-check ms-2">
                <input class="form-check-input" type="radio" name="order" id="sortOrderAsc" value="asc">
                <label class="form-check-label" for="sortViews">
                    Возрастанию
                </label>
            </div>
        </div>
    </form>
</div>

{% cache 90 catalog_content %}
{% for card in cards %}
    {% include "cards/includes/card_preview.html" %}
{% endfor %}
{% endcache %}
{% endblock %}