anki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from cards import views
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('cards/', include('cards.urls')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


app_name = 'users'  # Пространство имен для приложения


urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),
    path('signup/', views.RegisterUser.as_view(), name='signup'),
    path('register_done/', views.RegisterDone.as_view(), name='register_done'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password_change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password_change_done/', views.UserPasswordChangeDone.as_view(), name='password_change_done'),
    path('profile_cards/', views.UserCardsView.as_view(), name='profile_cards'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset_form.html',
             email_template_name='users/password_reset_email.html',
             success_url = reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name = 'users/password_reset_confirm.html',
             success_url = reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset_done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name = 'users/password_reset_complete.html'),
         name='password_reset_complete'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class RegisterUserForm(UserCreationForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control'}))


    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'password', 'password2')
        labels = {
            'email': 'E-Mail',
            'first_name': 'Имя'
        }
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'})
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise ValidationError('Пароли не совпадают')
        return cd['password']


    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise ValidationError('Такая почта уже существует!')
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(
        disabled=True,
        label='Логин',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    email = forms.CharField(
        disabled=True,
        label='E-mail',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'})
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Старый пароль'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Новый пароль'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтвердите новый пароль'}))

users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import reverse_lazy
from  django.views.generic import CreateView, TemplateView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from cards.models import Card
# Create your views here.

class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

    def get_success_url(self):
        next_url = self.request.POST.get('next', '').strip()
        if next_url:
            return next_url
        return reverse_lazy('catalog')


class LogoutUser(LogoutView):
    next_page = reverse_lazy('users:login')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:register_done')


class RegisterDone(TemplateView):
    template_name = 'users/register_done.html'
    extra_context = {'title': 'Регистрация завершена!'}


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль пользователя'}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'users/password_change_form.html'
    success_url = reverse_lazy('users:password_change_done')


class UserPasswordChangeDone(TemplateView):
    template_name = 'users/password_change_done.html'
    extra_context = {'title': 'Пароль изменен успешно'}


class UserCardsView(ListView):
    model = Card
    template_name = 'users/profile_cards.html'
    context_object_name = 'cards'

    def get_queryset(self):
        return Card.objects.filter(author=self.request.user).order_by('-upload_date')

users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 col-md-6">
                <h2>Вход в систему</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                    <button type="submit" class="btn btn-dark">Войти</button>
                    <a href="{% url 'users:password_reset' %}">Забыли пароль</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 col-md-6">
               <h2>Ваш пароль успешно изменен</h2>
                <a href="{% url 'index' %}" class="btn btn-dark">Вернуться на главную</a>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-3">
                <nav id="navbar-example3" class="flex-column align-items-stretch pe-3">
                    <nav class="nav nav-pills flex-column">
                        <a class="nav-link bg-warning text-light" href="{% url 'users:profile' %}">Профиль</a>
                        <a class="nav-link bg-danger text-light" href="{% url 'users:password_change' %}">Сменить пароль</a>
                        <a class="nav-link bg-info text-light" href="{% url 'users:profile_cards' %}">Мои карточки</a>
                    </nav>
                </nav>
            </div>
            <div class="col-md-9">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-dark">Сменить пароль</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 col-md-6">
                <div class="alert alert-success" role="alert">
                    <h4 class="alert-heading">{% trans "Ваш пароль был успешно изменен" %}</h4>
                    <p>{% trans "Теперь вы можете войти с новым паролем" %}</p>
                    <a href="{% url 'users:login' %}" class="btn btn-dark">Войти</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 col-md-6">
                <h2>{% trans "Ввод нового пароля" %}</h2>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger" role="alert">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-dark">Изменить пароль</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 col-md-6">
                <h2>{% trans "Сброс пароля" %}</h2>
                <p>{% trans "На вашу электронную почту были отправлены инструкции по восстановлению пароля" %}</p>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}
{% autoescape off %}
Здравствуйте!

Мы получили запрос на сброс пароля для вашей учетной записи. Если вы не делали этот запрос,
пожалуйста, проигнорируйте это письмо.
Чтобы сбросить ваш пароль, нажмите на ссылку ниже (или скопируйте и вставьте URL в ваш браузер):
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Эта ссылка для сброса пароля будет действительна в течении {{ expiration_days }} дней.

С уважением,
Команда {{ site_name }}
{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 col-md-6">
                <h2>{% trans "Восстановление пароля" %}</h2>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <div class="form-text">{{ field.help_text }}</div>
                            {% endif %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-dark">{% trans "Сбросить пароль" %}</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-3">
                <nav id="navbar-example3" class="flex-column align-items-stretch pe-3">
                    <nav class="nav nav-pills flex-column">
                        <a class="nav-link bg-warning text-light" href="{% url 'users:profile' %}">Профиль</a>
                        <a class="nav-link bg-danger text-light" href="{% url 'users:password_change' %}">Сменить пароль</a>
                        <a class="nav-link bg-info text-light" href="{% url 'users:profile_cards' %}">Мои карточки</a>
                    </nav>
                </nav>
            </div>
            <div class="col-md-9">
                <div data-bs-spy="scroll" data-bs-target="#navbar-example3" data-bs-offset="0" class="scrollspy-example">
                    <div id="item-1">
                        {{ form.as_p }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/profile_cards.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-3">
                <nav id="navbar-example3" class="flex-column align-items-stretch pe-3">
                    <nav class="nav nav-pills flex-column">
                        <a class="nav-link bg-warning text-light" href="{% url 'users:profile' %}">Профиль</a>
                        <a class="nav-link bg-danger text-light" href="{% url 'users:password_change' %}">Сменить пароль</a>
                        <a class="nav-link bg-info text-light" href="{% url 'users:profile_cards' %}">Мои карточки</a>
                    </nav>
                </nav>
            </div>
            <div class="col-md-9">
                {% for card in cards %}
                    {% include "cards/includes/card_preview.html" %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 col-md-6">
                <h2>Регистрация</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                    <button type="submit" class="btn btn-dark">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register_done.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 col-md-6">
                <h2>Вы успешно зарегистрировались</h2>
                <a href="{% url 'users:login' %}">Авторизуйтесь</a>

            </div>
        </div>
    </div>
{% endblock %}